<a href="https://colab.research.google.com/github/mathcute/Data-Science/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Criando arrays com NumPy

In [ ]:
import numpy as np

data = [1, 2, 3, 10, 20, 30]

array = np.array(data)

print(array)

[ 1  2  3 10 20 30]


##Atributos de arrays

In [ ]:
data = [[10, 20, 30], [40, 60, 90]]

array = np.array(data)

print(array.ndim) #fornece o número de dimensoes do array
print(array.shape) #shape nos diz quantos elementos temos em cada dimensão

##Atributos de arrays - 2

In [ ]:
import numpy as geek

arr = [[1, 2, 3], [4, 5, 6]]
dimension = geek.ndim(arr)
print(dimension)

2


##Gerando Arrays

In [ ]:
print(np.zeros(10))

print(np.ones(10))

print(np.arange(20))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


##Gerando arrays com Métodos Built-in

In [ ]:
print(np.arange(0, 10, 2))

print(np.arange(0, 10, 1))

print(np.arange(0, 10, 3))

##Arrays Aleatórios

In [ ]:
print(np.random.rand(1))

print(np.random.rand(2))

print(np.random.rand(3))

[0.05884451]
[0.81274155 0.52243347]
[0.62305551 0.65387707 0.58512595]


##Arrays multidimensionais

In [ ]:
print(np.random.rand(1, 2))

print(np.random.rand(2, 3))

print(np.random.rand(3, 4))

[[0.22405723 0.80179501]]
[[0.95205042 0.15646463 0.95748298]
 [0.16850553 0.75155174 0.23304885]]
[[0.77216919 0.09500395 0.68630131 0.46635723]
 [0.90135788 0.05610969 0.11455445 0.58527441]
 [0.64108282 0.43626344 0.61260802 0.42579299]]


##Max e Min()

In [ ]:
vetor = np.random.rand(3)

print(vetor)

print(vetor.max())

print(vetor.min())

[0.24916363 0.40811157 0.47182919]
0.4718291899475322
0.24916362569386552
