<a href="https://colab.research.google.com/github/mathcute/Data-Science/blob/main/Numpy_Exerciocios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##1. Desenvolva um array NumPy com valores de 1 a 10 (inclusive) e, em seguida, reverta a ordem dos elementos.

In [ ]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(np.flipud(array))

[10  9  8  7  6  5  4  3  2  1]


##2. Crie dois arrays NumPy A e B de tamanho 5x5 preenchidos com números aleatórios e realize a multiplicação elemento a elemento entre eles.


In [ ]:
array_a = np.random.rand(5, 5)

array_b = np.random.rand(5, 5)

multiplicacao = np.dot(array_a, array_b)

print(multiplicacao)

[[0.98024385 0.9239942  0.77163046 1.25261082 0.98453536]
 [1.28132546 1.89022889 1.33635797 1.99821838 1.58429218]
 [0.94607169 1.49973545 1.37845207 1.55077119 1.35857473]
 [1.42034813 1.03994921 1.1421982  1.63702184 2.27308807]
 [1.50867916 1.39671611 0.97615542 1.71704513 1.17776234]]


##3. Faça um array NumPy com números aleatórios e calcule a média, o desvio padrão e a mediana dos valores (funções mean, std e median).


In [ ]:
array_a = np.random.rand(5, 5)

array_b = np.random.rand(5, 5)

media_a = (np.mean(array_a))

media_b = (np.mean(array_b))

desvio_padrao_a = (np.std(array_a))

desvio_padrao_b = (np.std(array_b))

mediana_a = (np.mean(array_a))

mediana_b = (np.mean(array_b))

##4. Faça um array NumPy com valores de 0 a 9 e, em seguida, crie um novo array que contenha apenas os elementos pares do array original.

In [ ]:
array = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
array2 = []

for i in range(len(array)):

  if (array[i] % 2 == 0):

    array2.append(array[i])

print(array2)

[0, 2, 4, 6, 8]


##5. Crie um array NumPy com números aleatórios e substitua todos os valores negativos por zero.


In [ ]:
array = np.random.rand(2)

for i in range(len(array)):

  if (array[i] < 0):

    array[i] = 0

print(array)

[0.03422733 0.68584741]


##6. Crie um array NumPy com valores aleatórios inteiros entre 1 e 100 (inclusive) e encontre os seguintes estatísticas:
a) Média
b) Desvio padrão
c) Mediana
d) Valor mínimo
e) Valor máximo

In [ ]:
import numpy as np

array = np.random.randint(0, 100, size = 10)

media = np.mean(array)

desvio_padrao = np.std(array)

mediana = np.median(array)

min = np.min(array)

max = np.max(array)

print(max)

94
