<a href="https://colab.research.google.com/github/mathcute/Data-Science/blob/main/Numpy_Exerciocios2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##6. Crie um array NumPy com valores aleatórios inteiros entre 1 e 100 (inclusive) e encontre os seguintes estatísticas:
a) Média
b) Desvio padrão
c) Mediana
d) Valor mínimo
e) Valor máximo

In [ ]:
import numpy as np

array = np.random.randint(0, 100, size = 10)

media = np.mean(array)

desvio_padrao = np.std(array)

mediana = np.median(array)

min = np.min(array)

max = np.max(array)

print(max)

94


##7. Crie um array NumPy de 100 elementos inteiros aleatórios entre 1 e 10 (inclusive). Em seguida, calcule a soma cumulativa dos elementos.

In [ ]:
array = np.random.randint(1, 10, size = 10)

array_soma = np.cumsum(array)

print(array_soma)

[ 5  6  7 12 15 24 27 32 37 40]


##8. Crie um array NumPy de números inteiros de 1 a 20 (inclusive), excluindo os múltiplos de 3. Em seguida, encontre a soma dos elementos desse array

In [ ]:
array = np.random.randint(1, 20, size = 10)

for i in range(len(array)):

  if (array[i] % 3 == 0):

    array[i].remove(array)

    array[i].sum(array)

##9. Desenvolva dois arrays NumPy A e B de tamanho 5x5 preenchidos com números aleatórios inteiros entre 1 e 10. Realize a multiplicação de matriz.

In [ ]:
array_a = np.random.randint(1, 10, size = (5, 5))

array_b = np.random.randint(1, 10, size = (5, 5))

multiplicacao = np.dot(array_a, array_b)

print(multiplicacao)

[[134 167 226 183 142]
 [ 69 129 143 121 122]
 [ 94 102 131 136  59]
 [130 180 206 209 149]
 [112 166 142 175 115]]


##10.Crie um array NumPy com valores de 0 a 9 e, em seguida, embaralhe seus elementos de forma aleatória.

In [ ]:
from random import shuffle

array = np.arange(9)

shuffle(array)

print(array)

[4 5 7 6 1 3 0 2 8]
